config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  get "users/:id" => "users#show"
  get "users/:id/chats" => "chats#index"
  post "users/:id/chats" => "chats#create"
  resource :me, controller: :me
  post "user_tags" => "user_tags#update"
  post "me/edit" => "me#edit"
  post "me/destroy" => "me#destroy"
  post "user_tags/create" => "user_tags#create"
  resources :user_tags, only: [:destroy]
  resources :tags, only: [] do
    resources :users, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :user_tags
    has_many :users,through: :user_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  mount_uploader :image, UserImageUploader
  
  has_many :user_tags
  has_many :tags, through: :user_tags
end

app/models/user_tag.rb
class UserTag < ApplicationRecord
  belongs_to :user
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #authenticate_user!は、ログインしていない場合にログインページにリダイレクトさせるヘルパーメソッドです。
  protect_from_forgery with: :exception
  
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :email, :name, :image, :job_seeker, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  #authenticate_user!は、ログインしていない場合にログインページにリダイレクトさせるヘルパーメソッドです。
  before_filter :authenticate_user!
     def index
         @receiver_id = params[:id]
         @chats = Chat.where(sender_id: current_user.id, receiver_id: @receiver_id).or(Chat.where(sender_id: @receiver_id, receiver_id: current_user.id))
     end
     def create
        @chat =Chat.new(content: params[:content], sender_id: current_user.id,receiver_id: params[:id])
        @chat.save
        redirect_to("/users/#{params[:id]}/chats")
     end
     
  private
end

app/controllers/me_controller.rb
class MeController < ApplicationController
  #authenticate_user!は、ログインしていない場合にログインページにリダイレクトさせるヘルパーメソッドです。
  before_filter :authenticate_user!
  
  def show
    @user = current_user
  end
  def edit
    @user = current_user
    @user_tags = @user.user_tags
  end
  def update
    @user = current_user
    @user.update(user_params)
    redirect_to edit_me_path
  end
  
  private
  
  def user_params
    params.require(:user).permit(:image, :name, :description, :opinion, :email , :birthday, :region)
  end
end

app/controllers/user_tags_controller.rb
class UserTagsController < ApplicationController
    def create
      tag_name = params[:tag_name]
      tag = Tag.find_by(name: tag_name)
      if tag.nil?
        tag = Tag.new(name: tag_name)
        tag.save
      end
      user_tag = UserTag.find_by(user_id: current_user.id, tag_id: tag.id)
      if user_tag.nil?
        user_tag = UserTag.new(user_id: current_user.id, tag_id: tag.id)
        user_tag.save
      end
      redirect_to("/me/edit")
    end
    
    def destroy
      user_tag = UserTag.find(params[:id])
      user_tag.destroy
      redirect_to("/me/edit")
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #authenticate_user!は、ログインしていない場合にログインページにリダイレクトさせるヘルパーメソッドです。
  before_filter :authenticate_user!
  
  def index
    if params[:tag_id].present?
      @tag = Tag.find(params[:tag_id])
      @users = @tag.users.where.not(id: current_user.id)
    else
      @users = User.where.not(id: current_user.id)
    end
    @tags = Tag.all
  end
  def show 
    @user = User.find_by(id: params[:id])
  end
  
  private
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_tags_helper.rb
module UserTagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/index.html.erb
<div class="container">
  <% @chats.each do |chat|  %>   
    <div class="row">
  　　<% if chat.sender_id == current_user.id %>
  　　    <div class="col-5"></div>
        <div class="col-6">
          <div class="card my-2">
            <div class="card-body text-end">
              <%= chat.content %>
            </div>
          </div>
        </div>
  　　<% else %>
　　    <div class="col-6">
          <div class="card my-2">
            <div class="card-body">
              <%= chat.content %>
            </div>
          </div>
        </div>
　  　<% end %>
    </div>
  <% end %> 
  <%= form_tag ("/users/#{@receiver_id}/chats") do %> 
    <div class="form-group mr-3">
      <textarea name="content" rows="5" class="form-control" id="InputAsk"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">送信</button>
  
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kariitigou</title>
    <%= csrf_meta_tags %>
    <title>逆求人サイト　わがまま。</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  </head>

  <body>
    <%= render partial: "shared/header" %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>

app/views/me/edit.html.erb
<div class="container">
    <h2>プロフイール設定</h2> 
    <hr>
    
    <h5>プロフィール画像</h5>
    <%= form_for(@user, url: me_path) do |f| %>
    <%= image_tag(@user.image_url, width: '200') if @user.image? %>
     
    <%= f.file_field :image %>
    <a>設定できる画像は、5MB以内・JPG/PNG/GIF形式です。</a>
    
    <hr>
    
    <h5>ニックネーム</h5>
    <h6><%= f.text_field :name, class: 'form-control' %></h6>
   
    <hr>
    
    
    
    <h5>やってきたこと</h5>
      
      <%= f.text_area :description, class: 'form-control' %>
    
    
    <hr>
    <h5>伝えたいこと</h5>
   
      <%= f.text_area :opinion, class: 'form-control' %>
   
    
    <hr>
    
    <h5>登録メールアドレス</h5>
     <%= f.text_field :email, class: 'form-control' %>
    <hr>
    <h5>生年月日</h5>
    <%= f.date_field :birthday, class: 'form-control' %>
    <hr>
    
    <h5>お住まいの地域</h5>
        
  
    
    <a>都道府県</a>
        <%= f.select :region, {'北海道': '北海道', '東北': '東北', '関東': '関東','中部': '中部','近畿': '近畿','中国': '中国','四国': '四国','九州': '九州','沖縄': '沖縄','その他': 'その他'}, {}, { class: 'form-control' , required: true } %>

    <%= f.submit '保存', class: "btn btn-outline-primary" %>
    <% end %>
    <hr>

    <h5>タグ編集</h5>
     <% @user_tags.each do |user_tag| %>
       <span class="badge bg-light text-dark">
         <%= user_tag.tag.name %>  
       </span><span class="badge bg-secondary"><%= user_tag.tag.user_tags.count %></span>
       <%= link_to user_tag_path(user_tag.id), method: 'delete' do %>
           <button type="button" class="btn-close" aria-label="Close"></button>
        <% end %>
     <% end %>
         
        <%= form_tag("/user_tags/create", method: "post", remote: true) do %>
            <input class="form-control" type="text"  name="tag_name" aria-label="default input example">
            <button type="submit" class="btn btn-primary btn-sm">追加する</button>
        <% end %>
        <hr> 
</div>

app/views/me/show.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h2>プロフイール</h2>
        </div>
         <div class="col">
            <%= link_to edit_me_path, class: 'w-100 float-end' do %>
                <button type="submit" class="btn btn-primary btn-sm">編集する</button>
            <% end %>
        </div>
    </div>
    <hr>   
    <%= image_tag(@user.image_url, width: '200') if @user.image? %>
    


    
    <hr>
    
    <h5>ニックネーム</h5>
    <h6><%= @user.name %></h6>
   
    <hr>
    
     <span class="badge bg-light text-dark">エンジニア</span><span class="badge bg-secondary"></span>
     <span class="badge bg-light text-dark">周</span><span class="badge bg-secondary"></span>
    <span class="badge bg-light text-dark">バイト</span><span class="badge bg-secondary"></span>
    <hr> 
    
    <h5>やってきたこと</h5>
    <p><%= h(@user.description).gsub(/\R/, "<br>").html_safe %></p>
    
    <hr>
    <h5>伝えたいこと</h5>
    <p><%=  h(@user.opinion).gsub(/\R/, "<br>").html_safe %></p>
    <hr>
    
    <h5>登録メールアドレス</h5>
    <p><%= @user.email %></p>
    
   
    <h5>生年月日</h5>
    <p><%= @user.birthday.strftime("%Y/%-m/%-d") %></p>
      

    <hr>
    
   
    
    
</div>

app/views/shared/_header.html.erb
<div class="container">
    <div class="row mt-3">
        <div class="col-7"><a href="/" class="text-decoration-none text-body"><h1>逆求人サイト　わがまま</h1></a></div>
        <div class="col-5">
            <div class="d-flex flex-row-reverse">
                <% if user_signed_in? %>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-light' %>
                <% else %>
                  <%= link_to "ログイン", new_user_session_path, class: 'btn btn-light' %>
                <% end %>
                <a href="/me" class="btn btn-danger">プロフィール</a>
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16" style="color: black">
                  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                </svg>
            </div>
        </div>
    </div>
</div>
<ul class="nav justify-content-center">
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" href="#">逆求人を探す</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">求人を探す</a>
  </li>
</ul>
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
--> <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">人を探す</a>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">全国</a>
        </li>
          <a class="nav-link active" aria-current="page" href="#">北海道</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">東北</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">関東</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">中部</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">近畿</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">中国</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">四国</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">九州</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">沖縄</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">その他</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">絞り込みで探す</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/users/edit.html.erb
<div class="container">
    <h2>プロフイール設定</h2>
    
    <hr>
    
    <h5>プロフィール画像</h5>
    <%= form_for(@user) do |f| %>
    <%= image_tag(@user.image_url, width: '200') if @user.image? %>
     
    <%= f.file_field :image %>
    <a>設定できる画像は、5MB以内・JPG/PNG/GIF形式です。</a>
    
    <hr>
    
    <h5>ニックネーム</h5>
    <h6><%= f.text_field :name, class: 'form-control' %></h6>
   
    <hr>
    
     <h5>タグ編集</h5>
     <span class="badge bg-light text-dark">エンジニア</span><span class="badge bg-secondary">110</span>
   　 <button type="button" class="btn-close" aria-label="Close"></button>
     <span class="badge bg-light text-dark">週４</span><span class="badge bg-secondary">82</span>
     <button type="button" class="btn-close" aria-label="Close"></button>
     <button type="button" class="btn btn-light text-dark">
          海外<span class="badge bg-secondary">24</span>
     </button>
     <button type="button" class="btn-close" aria-label="Close"></button>
     <button type="button" class="btn btn-light text-dark">
          出張無し<span class="badge bg-secondary">23</span>
     </button>
     <button type="button" class="btn-close" aria-label="Close"></button>
    <input class="form-control" type="text"  aria-label="default input example">
    <button type="button" class="btn btn-primary btn-sm">追加する</button>
    <hr> 
    
    <h5>やってきたこと</h5>
      
      <%= f.text_area :description, class: 'form-control' %>
    
    
    <hr>
    <h5>伝えたいこと</h5>
   
      <%= f.text_area :opinion, class: 'form-control' %>
   
    
    <hr>
    
    <h5>登録メールアドレス</h5>
     <%= f.text_field :email, class: 'form-control' %>
    <hr>
    <h5>生年月日</h5>
    <%= f.date_field :birthday, class: 'form-control' %>
    <hr>
    
    <h5>お住まいの地域</h5>
        
  
    
    <a>都道府県</a>
        <%= f.select :region, {'北海道': '北海道', '東北': '東北', '関東': '関東','中部': '中部','近畿': '近畿','中国': '中国','四国': '四国','九州': '九州','沖縄': '沖縄','その他': 'その他'}, {}, { class: 'form-control' , required: true } %>

    <%= f.submit '保存', class: "btn btn-outline-primary" %>
    <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="my-3">
    <% @tags.each do |tag| %>
      <%= link_to tag_users_path(tag) do %>
        <span class="badge bg-light text-dark"><%= tag.name %></span><span class="badge bg-secondary"><%= tag.user_tags.count %></span>
      <% end %>
    <% end %>
  </div>
  <div class="row">
    <% @users.each do |user| %>
      <div class="col-2">
        <div class="card">
          <img src="https://ssth.dmc.nico/thumbnail/20210616/22/25/nicolive-production-pg38344745550431/nicolive-production-pg38344745550431_352_198.jpg" class="card-img-top">
          <div class="card-body">
            <div class="row">
                <div class="col-4"><img src="https://secure-dcdn.cdn.nimg.jp/nicoaccount/usericon/11851/118512194.jpg?1623832810" width="100%" /></div>
                <div class="col-8"><h5 class="card-title"><%= user.name %></h5></div>
            </div>
            <p class="card-text"><span class="badge bg-light text-dark">土日休み</span><span class="badge bg-light text-dark">契約社員</span><span class="badge bg-light text-dark">猫</span></p>
            <%= link_to("詳細を見る","/users/#{user.id}", class: 'btn btn-primary') %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="d-flex justify-content-center mt-3">
        <nav aria-label="Page navigation example">
          <ul class="pagination">
            <li class="page-item">
              <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">4</a></li>
            <li class="page-item"><a class="page-link" href="#">5</a></li>
            <li class="page-item">
              <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          </ul>
        </nav>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <%= image_tag(@user.image_url, width: '200') if @user.image? %>
    <h2><%= @user.name %></h2>
      <span class="badge bg-light text-dark">エンジニア</span><span class="badge bg-secondary"></span>
   
     <span class="badge bg-light text-dark">週４</span><span class="badge bg-secondary"></span>
     <button type="button" class="btn btn-light text-dark">
          海外<span class="badge bg-secondary"></span>
     </button>
     
     <button type="button" class="btn btn-light text-dark">
          出張無し<span class="badge bg-secondary"></span>
     </button>
      <span class="badge bg-light text-dark">エンジニア</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">月給25万以上</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">週４</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">土日休み</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">日商簿記二級</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">サービス業</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">配達</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">シフト制</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">残業10時間以内</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">昼出勤</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">週２０時間</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">時給２０００円以上</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">事務</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">月給25万以上</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">週４</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">土日休み</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">日商簿記二級</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">サービス業</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">配達</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">シフト制</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">残業10時間以内</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">昼出勤</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">週２０時間</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">時給２０００円以上</span><span class="badge bg-secondary"></span>
        <span class="badge bg-light text-dark">事務</span><span class="badge bg-secondary"></span>
           
           
        <hr>
        <h5>やってきたこと</h5>
        <p><%= h(@user.description).gsub(/\R/, "<br>").html_safe %></p>
    
        <hr>
        <h5>伝えたいこと</h5>
        <p><%=  h(@user.opinion).gsub(/\R/, "<br>").html_safe %></p>
        <hr>
       

    <div class="d-grid gap-2">
      <%= link_to("会話する","/users/#{@user.id}/chats", class: 'btn btn-success') %>
    </div>
    
</div>